MAIN_DIR: 'C:\Users\tanuz\Desktop\REPO-2022\AIC22_Track1_MTMC_ID10\'
DET_SOURCE_DIR: 'datasets/AIC22_Track1_MTMC_Tracking/test/S06/images/test/S06'
REID_MODEL: 'models/reid/resnet101_ibn_a_3.pth'
REID_BACKBONE: 'resnet101_ibn_a'
DET_IMG_DIR: 'datasets/test_reproduce/'         # same as DATA_DIR
OUTPUT_DIR: 'datasets/test_reproduce/detect_reid3/'   # dst dir
REID_SIZE_TEST: [384, 384]